baseURL = 'https://iqnev.github.io/'
languageCode = 'en-us'
title = 'Codes are a puzzle'
paginate = 3
theme = ["maverick","hugo-notice"]


[permalinks]
  pages = "/:slug"

[params]
  logo = '/images/favicon.ico'
  description = "A minimal hugo theme focus on content"
  author = 'Calvin Tran'

  [params.comments]
    theme = 'github-light'

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = "-120"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -201

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    style = 'xcode-dark'
    tabWidth = 4
    noClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]

